// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getFeed = `-- name: GetFeed :one
SELECT
        id
        ,created_at
        ,updated_at
        ,name
        ,url
FROM    feeds
WHERE   url = $1
`

type GetFeedRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
}

func (q *Queries) GetFeed(ctx context.Context, url string) (GetFeedRow, error) {
	row := q.db.QueryRowContext(ctx, getFeed, url)
	var i GetFeedRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
	)
	return i, err
}
