// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_post_by_url.sql

package database

import (
	"context"
)

const getPostByUrl = `-- name: GetPostByUrl :one
SELECT
            posts.id
            ,posts.created_at
            ,posts.updated_at
            ,posts.title
            ,posts.url
            ,posts.description
            ,posts.published_at
            ,posts.feed_id
FROM        posts
WHERE       posts.url = $1
`

func (q *Queries) GetPostByUrl(ctx context.Context, url string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByUrl, url)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}
